FUNCTION(LEADING_ZERO OUT_VARIABLE FINAL_MIN_LENGTH VALUE)
    STRING(LENGTH "${VALUE}" VALUE_LENGTH)
    MATH(EXPR REQUIRED_LEAD_ZERO_COUNT "${FINAL_MIN_LENGTH} - ${VALUE_LENGTH}")
    SET(LEAD_ZERO_VALUE ${VALUE})

    IF (REQUIRED_LEAD_ZERO_COUNT GREATER 0)
        MATH(EXPR REQUIRED_MINUS_ONE "${REQUIRED_LEAD_ZERO_COUNT} - 1")
        FOREACH (FOO RANGE ${REQUIRED_MINUS_ONE})
            SET(LEAD_ZERO_VALUE "0${LEAD_ZERO_VALUE}")
        ENDFOREACH (FOO)
    ENDIF (REQUIRED_LEAD_ZERO_COUNT GREATER 0)

    SET(${OUT_VARIABLE} "${LEAD_ZERO_VALUE}" PARENT_SCOPE)
ENDFUNCTION(LEADING_ZERO)
