.TH DIURNA_DESTROY 3 2021-10-13 "" "Linux Programmer's Manual"
.SH NAME
diurna_destroy \- Destroys Diurna
.SH LIBRARY
Diurna C Library (diurna, -ldiurna)
.SH SYNOPSIS
.nf
.B #include <diurna.h>
.PP
.BI ""void " diurna_destroy(" void ");
.SH DESCRIPTION
The
.BR diurna_destroy()
function terminates the Diurna logging library. It flushes all remaining messages and destroys the Diurna global context.
.SH RETURN VALUE
On success,
.BR diurna_destroy()
returns zero; on error, it returns an error number.
.SH ERRORS
.BR diurna_destroy()
can fail with the following error:
.TP
.B DIURNA_E_NOINIT
Diurna is not initialized.
.SH SEE ALSO
.ad l
.nh
.BR diurna_initialize (3),
.BR diurna_initialize_ex (3),
.BR diurna_destroy (3),
.BR diurna_cfg_appender_register (3),
.BR diurna_cfg_appender_unregister_all (3),
.BR diurna_cfg_loglevel_set (3),
.BR diurna_version_as_int (3),
.BR diurna_version_as_str (3),
.BR diurna_debug (3),
.BR diurna_info (3),
.BR diurna_warn (3),
.BR diurna_error (3)
